export const TECHNICAL_DEPTH_TERMS: string[] = [
  "release",
  "version",
  "changelog",
  "patch",
  "bugfix",
  "regression",
  "vulnerability",
  "cve",
  "exploit",
  "kernel",
  "driver",
  "compiler",
  "runtime",
  "benchmark",
  "performance",
  "latency",
  "throughput",
  "protocol",
  "specification",
  "architecture",
  "implementation",
  "source code",
  "codigo fonte",
  "configuration",
  "configuracao",
  "deployment",
  "migration",
  "tutorial",
  "guide",
  "tutorial pratico",
  "documentation",
  "api",
  "sdk",
  "library",
  "biblioteca",
  "framework",
  "module",
  "package",
  "dependency",
  "build system",
  "continuous integration",
  "container",
  "kubernetes",
  "systemd",
  "wayland",
  "compositor",
  "filesystem",
  "encryption",
  "cryptography",
  "memory safety",
  "concurrency",
  "scheduler",
  "syscall"
];

export const OPEN_SOURCE_RELEVANCE_TERMS: string[] = [
  "open source",
  "open-source",
  "software livre",
  "codigo aberto",
  "foss",
  "floss",
  "gnu",
  "linux",
  "free software",
  "license",
  "licenca",
  "gpl",
  "lgpl",
  "agpl",
  "mit license",
  "apache license",
  "mozilla public license",
  "copyleft",
  "contributor",
  "contribuidor",
  "maintainer",
  "mantenedor",
  "upstream",
  "fork",
  "pull request",
  "merge request",
  "repository",
  "repositorio",
  "self-hosted",
  "self-hosting",
  "community edition",
  "foundation",
  "fundacao",
  "linux foundation",
  "apache software foundation",
  "free software foundation",
  "debian",
  "fedora",
  "arch linux",
  "ubuntu",
  "kde",
  "gnome",
  "mozilla",
  "postgresql",
  "kernel"
];

export const NEGATIVE_SIGNALS: string[] = [
  "celebrity",
  "celebridade",
  "sports",
  "esportes",
  "crypto price",
  "bitcoin price",
  "token price",
  "price prediction",
  "stock market",
  "stock price",
  "shares",
  "ipo",
  "earnings call",
  "funding round",
  "series a",
  "series b",
  "venture capital",
  "valuation",
  "startup funding",
  "press release",
  "sponsored",
  "sponsored content",
  "advertisement",
  "advertorial",
  "affiliate",
  "discount",
  "coupon",
  "deal of the day",
  "black friday",
  "giveaway",
  "smartphone rumor",
  "phone leak",
  "iphone rumor",
  "gaming console",
  "console exclusive",
  "nft",
  "web3 hype",
  "metaverse",
  "ai hype",
  "revolutionary ai",
  "game changer",
  "you won't believe",
  "clickbait",
  "horoscope",
  "lifestyle",
  "celebridade gospel"
];
